<?php

namespace Database\Seeders;

use App\Models\Enums\ProductStatus;
use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin = User::query()->where('email', 'admin@camera.test')->first() ?? User::query()->first();
        $categories = Category::all()->keyBy('name');
        $brands = Brand::all()->keyBy('name');

        $productsData = [
            [
                'name' => 'Sony Alpha A7 IV Body',
                'sku' => 'SON-A7M4',
                'category' => 'Mirrorless',
                'brand' => 'Sony',
                'price' => 54990000,
                'original_price' => 59990000,
                'stock' => 15,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'Full-frame Exmor R CMOS 33.0 MP',
                    'resolution_mp' => '33.0',
                    'mount' => 'Sony E-mount',
                    'iso_range' => '100 - 51,200 (Mở rộng 50 - 204,800)',
                    'video' => '4K 60p 10-bit 4:2:2 All-Intra, S-Cinetone',
                    'screen' => '3.0 inch LCD cảm ứng lật xoay đa góc 1.03 triệu điểm',
                    'weight_g' => 658,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Máy ảnh Mirrorless Hybrid toàn diện đỉnh cao của Sony với cảm biến 33MP thế hệ mới, lấy nét Real-time Eye AF thông minh cho cả người, động vật và chim.',
            ],
            [
                'name' => 'Sony Alpha A7R V Body',
                'sku' => 'SON-A7R5',
                'category' => 'Mirrorless',
                'brand' => 'Sony',
                'price' => 84990000,
                'original_price' => 92990000,
                'stock' => 8,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'Full-frame Exmor R BSI CMOS 61.0 MP',
                    'resolution_mp' => '61.0',
                    'mount' => 'Sony E-mount',
                    'iso_range' => '100 - 32,000 (Mở rộng 50 - 102,400)',
                    'video' => '8K 24p, 4K 60p 10-bit 4:2:2',
                    'screen' => '3.2 inch màn hình cảm ứng 4 trục độc quyền',
                    'weight_g' => 723,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Độ phân giải siêu cao 61MP kết hợp vi xử lý AI chuyên dụng cho khả năng nhận diện chủ thể vượt bậc và chống rung lên tới 8 stops.',
            ],
            [
                'name' => 'Sony Cinema Line FX3',
                'sku' => 'SON-FX3',
                'category' => 'Mirrorless',
                'brand' => 'Sony',
                'price' => 93990000,
                'original_price' => 99990000,
                'stock' => 5,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'Full-frame Exmor R CMOS 12.1 MP',
                    'resolution_mp' => '12.1',
                    'mount' => 'Sony E-mount',
                    'iso_range' => '80 - 102,400 (Mở rộng lên đến 409,600)',
                    'video' => '4K 120p không giới hạn thời gian ghi hình, quạt tản nhiệt tích hợp',
                    'screen' => '3.0 inch LCD cảm ứng xoay lật đa hướng',
                    'weight_g' => 715,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Máy quay điện ảnh nhỏ gọn dành riêng cho các nhà làm phim chuyên nghiệp và videographer du lịch với dải dynamic range hơn 15 stops.',
            ],
            [
                'name' => 'Sony ZV-E10 Body',
                'sku' => 'SON-ZVE10',
                'category' => 'Mirrorless',
                'brand' => 'Sony',
                'price' => 15490000,
                'original_price' => 16990000,
                'stock' => 25,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'APS-C Exmor CMOS 24.2 MP',
                    'resolution_mp' => '24.2',
                    'mount' => 'Sony E-mount',
                    'iso_range' => '100 - 32,000',
                    'video' => '4K 30p oversampled 6K, FHD 120p',
                    'screen' => '3.0 inch LCD cảm ứng xoay lật selfie',
                    'weight_g' => 343,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Máy ảnh thiết kế tối ưu cho Vlogger và người sáng tạo nội dung với micro định hướng 3 capsule và chế độ Product Showcase tiện lợi.',
            ],
            [
                'name' => 'Canon EOS R5 Mark II Body',
                'sku' => 'CAN-R5M2',
                'category' => 'Mirrorless',
                'brand' => 'Canon',
                'price' => 99990000,
                'original_price' => 105000000,
                'stock' => 6,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'Full-frame Back-Illuminated Stacked CMOS 45 MP',
                    'resolution_mp' => '45.0',
                    'mount' => 'Canon RF',
                    'iso_range' => '100 - 51,200',
                    'video' => '8K 60p RAW, 4K 120p, chống rung trong thân máy 8.5 stops',
                    'screen' => '3.2 inch cảm ứng xoay lật góc rộng',
                    'weight_g' => 746,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Siêu phẩm flagship của Canon trang bị chip tăng tốc Accelerated Capture xử lý dữ liệu cực đại và công nghệ lấy nét điều khiển bằng mắt Eye Control AF tân tiến.',
            ],
            [
                'name' => 'Canon EOS R6 Mark II Body',
                'sku' => 'CAN-R6M2',
                'category' => 'Mirrorless',
                'brand' => 'Canon',
                'price' => 59990000,
                'original_price' => 64990000,
                'stock' => 12,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'Full-frame CMOS 24.2 MP',
                    'resolution_mp' => '24.2',
                    'mount' => 'Canon RF',
                    'iso_range' => '100 - 102,400',
                    'video' => '4K 60p oversampled không crop, 6K RAW qua cổng HDMI',
                    'screen' => '3.0 inch LCD xoay lật 1.62 triệu điểm',
                    'weight_g' => 670,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Khả năng chụp liên tục 40fps điện tử, lấy nét Dual Pixel CMOS AF II nhận dạng chuẩn xác xe hơi, tàu hỏa, máy bay, ngựa và chó mèo.',
            ],
            [
                'name' => 'Canon EOS R8 Body',
                'sku' => 'CAN-R8',
                'category' => 'Mirrorless',
                'brand' => 'Canon',
                'price' => 31990000,
                'original_price' => 34990000,
                'stock' => 18,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 12,
                'specs' => [
                    'sensor_type' => 'Full-frame CMOS 24.2 MP',
                    'resolution_mp' => '24.2',
                    'mount' => 'Canon RF',
                    'iso_range' => '100 - 102,400',
                    'video' => '4K 60p oversampling từ 6K',
                    'screen' => '3.0 inch màn hình cảm ứng xoay lật',
                    'weight_g' => 461,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Máy ảnh full-frame nhẹ nhất dòng EOS R của Canon, đem lại chất lượng hình ảnh cấp độ chuyên nghiệp trong thân máy siêu nhỏ gọn.',
            ],
            [
                'name' => 'Canon EOS 5D Mark IV Body',
                'sku' => 'CAN-5DM4',
                'category' => 'DSLR',
                'brand' => 'Canon',
                'price' => 49990000,
                'original_price' => 55000000,
                'stock' => 0, // Yêu cầu: stock = 0
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 12,
                'specs' => [
                    'sensor_type' => 'Full-frame CMOS 30.4 MP',
                    'resolution_mp' => '30.4',
                    'mount' => 'Canon EF',
                    'iso_range' => '100 - 32,000 (Mở rộng 50 - 102,400)',
                    'video' => '4K Motion JPEG 30p',
                    'screen' => '3.2 inch Clear View II LCD cảm ứng',
                    'weight_g' => 890,
                    'condition' => 'Mới 100% Tồn kho (Đã ngừng sản xuất)',
                ],
                'description' => 'Huyền thoại DSLR full-frame được ưa chuộng nhất của Canon phục vụ các studio chụp ảnh cưới và phóng sự sự kiện bền bỉ trong mọi điều kiện thời tiết.',
            ],
            [
                'name' => 'Nikon Z8 Body',
                'sku' => 'NIK-Z8',
                'category' => 'Mirrorless',
                'brand' => 'Nikon',
                'price' => 91990000,
                'original_price' => 98990000,
                'stock' => 7,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'Full-frame Stacked CMOS 45.7 MP (Không màn trập cơ học)',
                    'resolution_mp' => '45.7',
                    'mount' => 'Nikon Z',
                    'iso_range' => '64 - 25,600 (Mở rộng 32 - 102,400)',
                    'video' => '8.3K 60p N-RAW, 4.1K 120p, ProRes RAW HQ',
                    'screen' => '3.2 inch màn hình lật nghiêng 4 trục',
                    'weight_g' => 910,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Sức mạnh của chiếc flagship Z9 thu nhỏ trong thân máy Z8 linh hoạt, loại bỏ màn trập cơ truyền thống giúp triệt tiêu hiện tượng rolling shutter.',
            ],
            [
                'name' => 'Nikon Z6 III Body',
                'sku' => 'NIK-Z6M3',
                'category' => 'Mirrorless',
                'brand' => 'Nikon',
                'price' => 64990000,
                'original_price' => 68990000,
                'stock' => 10,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'Full-frame Partially-Stacked CMOS 24.5 MP',
                    'resolution_mp' => '24.5',
                    'mount' => 'Nikon Z',
                    'iso_range' => '100 - 64,000',
                    'video' => '6K 60p N-RAW trong máy, 4K 120p',
                    'screen' => '3.2 inch cảm ứng xoay lật góc đa hướng',
                    'weight_g' => 760,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Dòng máy ảnh đầu tiên trên thế giới trang bị cảm biến Partially-Stacked, kính ngắm EVF siêu sáng 4000 nits màu sắc rực rỡ.',
            ],
            [
                'name' => 'Nikon Zf Body',
                'sku' => 'NIK-ZF',
                'category' => 'Mirrorless',
                'brand' => 'Nikon',
                'price' => 47990000,
                'original_price' => 51990000,
                'stock' => 14,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'Full-frame BSI CMOS 24.5 MP',
                    'resolution_mp' => '24.5',
                    'mount' => 'Nikon Z',
                    'iso_range' => '100 - 64,000',
                    'video' => '4K 60p 10-bit H.265',
                    'screen' => '3.2 inch cảm ứng xoay lật hoàn toàn',
                    'weight_g' => 710,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Thiết kế hoài cổ lấy cảm hứng từ chiếc máy ảnh phim Nikon FM2 huyền thoại, tích hợp các vòng xoay cơ học bằng đồng thau chạm khắc tinh xảo.',
            ],
            [
                'name' => 'Nikon D850 Body',
                'sku' => 'NIK-D850',
                'category' => 'DSLR',
                'brand' => 'Nikon',
                'price' => 52990000,
                'original_price' => 58000000,
                'stock' => 0, // Yêu cầu: stock = 0
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 12,
                'specs' => [
                    'sensor_type' => 'Full-frame BSI CMOS 45.7 MP',
                    'resolution_mp' => '45.7',
                    'mount' => 'Nikon F',
                    'iso_range' => '64 - 25,600 (Mở rộng 32 - 102,400)',
                    'video' => '4K UHD 30p không crop khung hình',
                    'screen' => '3.2 inch màn hình cảm ứng nghiêng 2.36 triệu điểm',
                    'weight_g' => 1005,
                    'condition' => 'Mới 100% Tồn kho',
                ],
                'description' => 'Đỉnh cao của công nghệ DSLR Nikon với thời lượng pin lên đến 1840 kiểu chụp mỗi lần sạc và dải dynamic range đạt kỷ lục của cảm biến BSI.',
            ],
            [
                'name' => 'Fujifilm X-T5 Body',
                'sku' => 'FUJ-XT5',
                'category' => 'Mirrorless',
                'brand' => 'Fujifilm',
                'price' => 41990000,
                'original_price' => 44990000,
                'stock' => 16,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'APS-C X-Trans CMOS 5 HR 40.2 MP',
                    'resolution_mp' => '40.2',
                    'mount' => 'Fujifilm X',
                    'iso_range' => '125 - 12,800',
                    'video' => '6.2K 30p 4:2:2 10-bit, F-Log2',
                    'screen' => '3.0 inch màn hình lật 3 chiều chuyên nhiếp ảnh tĩnh',
                    'weight_g' => 557,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Tập trung tuyệt đối vào nhiếp ảnh tĩnh với cảm biến 40.2MP độ nét vượt trội, 19 chế độ giả lập màu phim Film Simulation kinh điển.',
            ],
            [
                'name' => 'Fujifilm X100VI',
                'sku' => 'FUJ-X100VI',
                'category' => 'Compact',
                'brand' => 'Fujifilm',
                'price' => 47990000,
                'original_price' => 55000000,
                'stock' => 4,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'APS-C X-Trans CMOS 5 HR 40.2 MP',
                    'resolution_mp' => '40.2',
                    'mount' => 'Ống kính gắn liền Fujinon 23mm F2 II (Tương đương 35mm)',
                    'iso_range' => '125 - 12,800',
                    'video' => '6.2K 30p, chống rung trong thân máy IBIS 6.0 stops',
                    'screen' => '3.0 inch màn hình LCD cảm ứng lật nghiêng',
                    'weight_g' => 521,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Máy ảnh compact cao cấp được săn đón nhất toàn cầu kết hợp kính ngắm quang học lai Hybrid Viewfinder và 20 giả lập màu phim độc quyền Reala Ace.',
            ],
            [
                'name' => 'Fujifilm X-S20 Body',
                'sku' => 'FUJ-XS20',
                'category' => 'Mirrorless',
                'brand' => 'Fujifilm',
                'price' => 29990000,
                'original_price' => 32990000,
                'stock' => 11,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'APS-C X-Trans CMOS 4 26.1 MP',
                    'resolution_mp' => '26.1',
                    'mount' => 'Fujifilm X',
                    'iso_range' => '160 - 12,800',
                    'video' => '6.2K 30p, 4K 60p, chế độ Vlog chuyên dụng',
                    'screen' => '3.0 inch cảm ứng xoay lật góc tự do',
                    'weight_g' => 491,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Báng cầm sâu chắc chắn, thời lượng pin dung lượng lớn NP-W235 chụp 750 tấm, tích hợp chế độ Vlog chuyên nghiệp cho các nhà sáng tạo nội dung.',
            ],
            [
                'name' => 'Fujifilm Instax Mini Evo Hybrid',
                'sku' => 'FUJ-EVO',
                'category' => 'Instant',
                'brand' => 'Fujifilm',
                'price' => 5190000,
                'original_price' => 5490000,
                'stock' => 30,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 12,
                'specs' => [
                    'sensor_type' => '1/5-inch CMOS với bộ lọc màu cơ bản',
                    'resolution_mp' => '4.9',
                    'mount' => 'Ống kính gắn liền tiêu cự 28mm F2',
                    'iso_range' => '100 - 1600 tự động',
                    'video' => 'Không hỗ trợ (Chuyên chụp và in ảnh lấy ngay)',
                    'screen' => '3.0 inch TFT color LCD',
                    'weight_g' => 285,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Máy chụp ảnh lấy liền kết hợp in ấn kỹ thuật số với 100 hiệu ứng chụp sáng tạo từ 10 hiệu ứng ống kính và 10 hiệu ứng phim.',
            ],
            [
                'name' => 'Panasonic Lumix S5 II Body',
                'sku' => 'PAN-S5M2',
                'category' => 'Mirrorless',
                'brand' => 'Panasonic',
                'price' => 43990000,
                'original_price' => 48990000,
                'stock' => 9,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'Full-frame CMOS 24.2 MP với Phase Detection AF',
                    'resolution_mp' => '24.2',
                    'mount' => 'Leica L-mount',
                    'iso_range' => '100 - 51,200 (Dual Native ISO)',
                    'video' => '6K 30p 10-bit 4:2:0, C4K 60p không giới hạn ghi hình',
                    'screen' => '3.0 inch cảm ứng xoay lật 1.84 triệu điểm',
                    'weight_g' => 740,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Bước nhảy vọt lịch sử của Panasonic với hệ thống lấy nét theo pha PDAF lần đầu tiên xuất hiện cùng công nghệ chống rung Active I.S.',
            ],
            [
                'name' => 'Panasonic Lumix GH6 Body',
                'sku' => 'PAN-GH6',
                'category' => 'Mirrorless',
                'brand' => 'Panasonic',
                'price' => 38990000,
                'original_price' => 45000000,
                'stock' => 3,
                'status' => ProductStatus::HIDDEN, // Yêu cầu: status = hidden
                'warranty_months' => 12,
                'specs' => [
                    'sensor_type' => 'Micro Four Thirds Live MOS 25.2 MP',
                    'resolution_mp' => '25.2',
                    'mount' => 'Micro Four Thirds (MFT)',
                    'iso_range' => '100 - 25,600 (Dynamic Range Boost)',
                    'video' => '5.7K 60p, 4K 120p 10-bit, ghi trực tiếp Apple ProRes',
                    'screen' => '3.0 inch xoay lật đa góc kết hợp quạt làm mát',
                    'weight_g' => 823,
                    'condition' => 'Mới 100% (Sản phẩm demo tạm ẩn)',
                ],
                'description' => 'Máy quay phim Micro Four Thirds hàng đầu chuyên phục vụ quay video thương mại không giới hạn thời gian ghi hình nhờ quạt gió tản nhiệt cưỡng bức.',
            ],
            [
                'name' => 'Olympus OM System OM-1 Mark II Body',
                'sku' => 'OLY-OM1M2',
                'category' => 'Mirrorless',
                'brand' => 'Olympus',
                'price' => 53990000,
                'original_price' => 58000000,
                'stock' => 6,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 12,
                'specs' => [
                    'sensor_type' => 'Micro Four Thirds Cross Quad Pixel BSI Stacked CMOS 20.4 MP',
                    'resolution_mp' => '20.4',
                    'mount' => 'Micro Four Thirds (MFT)',
                    'iso_range' => '200 - 25,600 (Mở rộng 80 - 102,400)',
                    'video' => '4K 60p 10-bit OM-Log, FHD 240p High Speed',
                    'screen' => '3.0 inch LCD xoay lật cảm ứng 1.62 triệu điểm',
                    'weight_g' => 599,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Chuẩn kháng nước kháng bụi chuẩn IP53 cao cấp nhất ngành máy ảnh, hệ thống chụp liên tiếp 120fps và tính năng kính lọc ND kỹ thuật số Live GND độc đáo.',
            ],
            [
                'name' => 'GoPro HERO12 Black',
                'sku' => 'GOP-H12',
                'category' => 'Action Camera',
                'brand' => 'GoPro',
                'price' => 9490000,
                'original_price' => 10490000,
                'stock' => 40,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 12,
                'specs' => [
                    'sensor_type' => '1/1.9 inch CMOS tỉ lệ 8:7',
                    'resolution_mp' => '27.0',
                    'mount' => 'Chân gắn GoPro tiêu chuẩn & ren 1/4-20',
                    'iso_range' => '100 - 6400',
                    'video' => '5.3K 60p, 4K 120p, chống rung HyperSmooth 6.0 với AutoBoost',
                    'screen' => 'Màn hình cảm ứng sau 2.27 inch + Màn hình hiển thị trước 1.4 inch',
                    'weight_g' => 154,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Camera hành động mạnh mẽ nhất với khả năng chống nước sâu tới 10m không cần vỏ hộp, hỗ trợ kết nối âm thanh không dây qua tai nghe Bluetooth AirPods.',
            ],
            [
                'name' => 'Leica Q3',
                'sku' => 'LEI-Q3',
                'category' => 'Compact',
                'brand' => 'Leica',
                'price' => 165000000,
                'original_price' => null,
                'stock' => 2,
                'status' => ProductStatus::HIDDEN, // Yêu cầu: status = hidden
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'Full-frame BSI CMOS công nghệ Triple-Resolution 60/36/18 MP',
                    'resolution_mp' => '60.0',
                    'mount' => 'Ống kính gắn liền Leica Summilux 28mm f/1.7 ASPH có Macro',
                    'iso_range' => '50 - 100,000',
                    'video' => '8K 30p, C4K 60p 10-bit, sạc không dây',
                    'screen' => '3.0 inch màn hình cảm ứng nghiêng sắc nét 1.84 triệu điểm',
                    'weight_g' => 743,
                    'condition' => 'Mới 100% Nhập khẩu Đức',
                ],
                'description' => 'Kiệt tác quang học của nước Đức với ống kính Summilux 28mm f/1.7 danh tiếng, chất lượng ảnh đẳng cấp cùng thiết kế công thái học tinh giản sang trọng.',
            ],
            [
                'name' => 'Leica M11 Body Black',
                'sku' => 'LEI-M11',
                'category' => 'Mirrorless',
                'brand' => 'Leica',
                'price' => 225000000,
                'original_price' => null,
                'stock' => 1,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 24,
                'specs' => [
                    'sensor_type' => 'Full-frame BSI CMOS Triple Resolution (60MP/36MP/18MP)',
                    'resolution_mp' => '60.0',
                    'mount' => 'Leica M bayonet',
                    'iso_range' => '64 - 50,000',
                    'video' => 'Không hỗ trợ (Đặc trưng thuần cơ học chụp ảnh Rangefinder Leica M)',
                    'screen' => '2.95 inch kính sapphire bảo vệ 2.3 triệu điểm',
                    'weight_g' => 530,
                    'condition' => 'Mới 100% Nhập khẩu chính hãng',
                ],
                'description' => 'Biểu tượng nhiếp ảnh Rangefinder lấy nét điểm vàng đo xa, bộ nhớ trong tích hợp 64GB và nắp trên bằng nhôm xử lý anodized siêu nhẹ.',
            ],
            [
                'name' => 'Canon RF 24-70mm f/2.8L IS USM',
                'sku' => 'CAN-RF2470',
                'category' => 'Ống kính (Lens)',
                'brand' => 'Canon',
                'price' => 56990000,
                'original_price' => 61000000,
                'stock' => 8,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 12,
                'specs' => [
                    'sensor_type' => 'Tương thích máy ảnh Full-frame và APS-C Canon RF',
                    'resolution_mp' => 'Tối ưu độ phân giải cao trên 50MP',
                    'mount' => 'Canon RF',
                    'iso_range' => 'N/A (Ống kính khẩu độ f/2.8 liên tục)',
                    'video' => 'Động cơ Nano USM êm ái, mượt mà khi quay phim',
                    'screen' => 'Vòng điều khiển thông minh Control Ring gán chức năng',
                    'weight_g' => 900,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Ống kính zoom tiêu chuẩn đa dụng dòng L cao cấp của Canon, tích hợp chống rung quang học 5 stops và thấu kính tráng phủ Air Sphere Coating.',
            ],
            [
                'name' => 'Sony FE 24-70mm f/2.8 GM II',
                'sku' => 'SON-FE2470GM2',
                'category' => 'Ống kính (Lens)',
                'brand' => 'Sony',
                'price' => 49990000,
                'original_price' => 53990000,
                'stock' => 10,
                'status' => ProductStatus::ACTIVE,
                'warranty_months' => 12,
                'specs' => [
                    'sensor_type' => 'Tương thích cảm biến Full-frame và Super35 Sony E-mount',
                    'resolution_mp' => 'Chuẩn G Master đáp ứng cảm biến trên 60MP',
                    'mount' => 'Sony E-mount',
                    'iso_range' => 'N/A (Khẩu độ f/2.8 trên toàn dải tiêu cự)',
                    'video' => '4 động cơ tuyến tính XD Linear Motor siêu thanh',
                    'screen' => 'Vòng khẩu độ có nút gạt De-click chuyên dụng quay phim',
                    'weight_g' => 695,
                    'condition' => 'Mới 100% Chính Hãng',
                ],
                'description' => 'Ống kính zoom f/2.8 nhỏ và nhẹ nhất thế giới trong cùng phân khúc, giảm 20% trọng lượng so với thế hệ trước với độ sắc nét quang học vượt trội.',
            ],
        ];

        foreach ($productsData as $data) {
            $category = $categories->get($data['category']);
            $brand = $brands->get($data['brand']);

            if (!$category || !$brand) {
                continue;
            }

            $product = Product::query()->firstOrCreate(
                ['sku' => $data['sku']],
                [
                    'category_id' => $category->id,
                    'brand_id' => $brand->id,
                    'name' => $data['name'],
                    'slug' => Str::slug($data['name']),
                    'price' => $data['price'],
                    'original_price' => $data['original_price'],
                    'stock' => $data['stock'],
                    'description' => $data['description'],
                    'specs' => $data['specs'],
                    'warranty_months' => $data['warranty_months'],
                    'status' => $data['status'],
                    'created_by' => $admin?->id,
                ]
            );

            // Tạo ảnh đại diện chính cho sản phẩm
            ProductImage::query()->firstOrCreate(
                [
                    'product_id' => $product->id,
                    'is_primary' => true,
                ],
                [
                    'path' => 'products/' . Str::lower($product->sku) . '.jpg',
                    'sort_order' => 0,
                ]
            );
        }
    }
}
